[workspace]
resolver = "2"

members = [
    "wasm_codegen",
    "shared",
    "test-host",
    "test-guest",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
bincode = "1.3.3"
serde = { version = "1", features = ["derive"] }
