[package]
name = "wasm_codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
